### ISSUE TITLE
Local date times with unknown UTC offset assumed to be UTC time?

### ISSUE THREAD

**Issue by trevorld** [dgkf/parttime#48]
I'm noticing that `{parttime}` seems to automatically assume local datetimes with missing UTC offset to be UTC time.  Is this intentional or a "bug"?

```r
dt = as.parttime("2020-04-05T06:07:08")
as.matrix(dt)
```
```r
                    year month day hour min sec tzhour
2020-04-05T06:07:08 2020     4   5    6   7   8      0
```

Wouldn't it make more sense to have the `tzhour` be an `NA_real_` instead?

I'm also noticing that the only difference in the formatting of a datetime with a zero UTC offset and a missing UTC offset is some red color (if your terminal supports color).  Any reason not to put the "+00:00" in the format string perhaps with a space before the +/- like in the default Sql Server Datetimeoffset string format?

**Comment by dgkf** [comment]
Thanks for raising this. This is intentional, though I'm open to being swayed about default behaviors, and I always appreciate learning of what design choices might appear unintuitive.

When you load `parttime`, you should see a message like this:

```r
> library(parttime)
Initializing default timezone offset, which is assumed when timezone parts are missing.

    options("parttime.assume_tz_offset" = 0L)
    
```

Hopefully you saw this, and even if the default doesn't suit you, the actions to take to make it work for you are clear from this message.

The desired behavior here is a bit use-case dependent. On the one hand, if you frequently work with international datetimes, then it might be obvious that a datetime is partial if it lacks a timezone and then you would want that ambiguity reflected in comparisons by default. However, if you only work with local datetimes, then having an expression like `definitely(parttime("2022") < parttime("2023")) == FALSE` might feel unintuitive.

To accommodate these, a timezone is assumed. However, you can always override it using the option by providing a local timezone or `NA`.

Just in terms of history of the package, the central focus of the package was clinical data. Typically clinical datetime calculations occur on a local scale - for example, a patient's clinic visit's time since study start. Being assumptive about a timezone can be a helpful default just to minimize the repeated specifying of timezones.

**Comment by trevorld** [comment]
* Thanks for the info and reasoning!
* That message was printed out and I should have paid closer attention to it.
* I see now if you have a multiple datetimes in the vector some with missing UTC offsets and some with zero UTC offsets then we do observe a "-00:00" in the format string for those with a zero UTC offset.
* I'm trying [to add support converting to/from `{parttime}`](https://github.com/trevorld/r-datetimeoffset/issues/49) datetimes and am mainly trying to figure out the main differences between your class and my datetime class and the best way to go about the two-way conversions (it seems I should be working with the numeric matrix backing your datetime object?)

**Comment by dgkf** [comment]
Thanks for sharing your work in this space and for considering interop with `parttime`!  Just taking a quick peek, it definitely seems like conversion should be do-able, but there's always these edge cases about fractional seconds to/from nanoseconds + digits, etc. 

Feel free to keep filing issues if you have other questions!
